"""
Document Generator — Creates Word (.docx) and PowerPoint (.pptx) files from AI content.
"""
import io
import re
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_docx(content: str, title: str = "Document") -> io.BytesIO:
    """Generate a Word document from markdown-like content."""
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE

    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Add date subtitle
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = date_para.add_run(f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(128, 128, 128)
    run.font.italic = True

    doc.add_paragraph("")  # Spacer

    # Parse markdown content into document elements
    lines = content.split("\n")
    in_code_block = False
    code_lines = []
    code_lang = ""
    in_table = False
    table_rows = []

    for line in lines:
        # Code block handling
        if line.strip().startswith("```"):
            if in_code_block:
                # End code block
                code_text = "\n".join(code_lines)
                p = doc.add_paragraph()
                p.style = doc.styles["Normal"]
                p.paragraph_format.left_indent = Inches(0.3)
                run = p.add_run(code_text)
                run.font.name = "Consolas"
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(40, 40, 40)
                in_code_block = False
                code_lines = []
            else:
                in_code_block = True
                code_lang = line.strip().replace("```", "").strip()
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        # Table handling
        if "|" in line and line.strip().startswith("|"):
            cells = [c.strip() for c in line.split("|") if c.strip()]
            if all(set(c) <= set("- :") for c in cells):
                continue  # Skip separator row
            table_rows.append(cells)
            in_table = True
            continue
        elif in_table:
            # Flush table
            if table_rows:
                _add_table(doc, table_rows)
            table_rows = []
            in_table = False

        stripped = line.strip()

        # Headings
        if stripped.startswith("#### "):
            doc.add_heading(stripped[5:], level=4)
        elif stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        # Horizontal rule
        elif stripped.startswith("---"):
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(6)
            p.paragraph_format.space_after = Pt(6)
            run = p.add_run("_" * 50)
            run.font.color.rgb = RGBColor(200, 200, 200)
        # Bullet list
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:]
            text = _clean_bold_italic(text)
            p = doc.add_paragraph(style="List Bullet")
            _add_formatted_text(p, text)
        # Numbered list
        elif re.match(r"^\d+\.\s", stripped):
            text = re.sub(r"^\d+\.\s", "", stripped)
            text = _clean_bold_italic(text)
            p = doc.add_paragraph(style="List Number")
            _add_formatted_text(p, text)
        # Blockquote
        elif stripped.startswith("> "):
            text = stripped[2:]
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.5)
            run = p.add_run(text)
            run.font.italic = True
            run.font.color.rgb = RGBColor(100, 100, 100)
        # Empty line
        elif not stripped:
            continue
        # Normal paragraph
        else:
            p = doc.add_paragraph()
            _add_formatted_text(p, stripped)

    # Flush remaining table
    if table_rows:
        _add_table(doc, table_rows)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("Generated by AI Personal Assistant")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(160, 160, 160)
    run.font.italic = True

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def _add_table(doc, rows):
    """Add a formatted table to the document."""
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.table import WD_TABLE_ALIGNMENT

    if not rows:
        return
    cols = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=cols)
    table.style = "Light Grid Accent 1"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    for i, row_data in enumerate(rows):
        for j, cell_text in enumerate(row_data):
            if j < cols:
                cell = table.cell(i, j)
                cell.text = cell_text
                for paragraph in cell.paragraphs:
                    paragraph.style.font.size = Pt(10)
                    if i == 0:
                        for run in paragraph.runs:
                            run.bold = True


def _clean_bold_italic(text):
    """Remove markdown formatting for plain text."""
    return text


def _add_formatted_text(paragraph, text):
    """Add text with bold/italic markdown formatting to a paragraph."""
    # Split by bold markers
    parts = re.split(r"(\*\*\*.+?\*\*\*|\*\*.+?\*\*|\*.+?\*|`.+?`)", text)
    for part in parts:
        if part.startswith("***") and part.endswith("***"):
            run = paragraph.add_run(part[3:-3])
            run.bold = True
            run.italic = True
        elif part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        elif part.startswith("`") and part.endswith("`"):
            from docx.shared import Pt, RGBColor
            run = paragraph.add_run(part[1:-1])
            run.font.name = "Consolas"
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(99, 102, 241)
        else:
            paragraph.add_run(part)


def generate_pptx(content: str, title: str = "Presentation") -> io.BytesIO:
    """Generate a PowerPoint presentation from markdown-like content."""
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Color scheme
    primary = RGBColor(99, 102, 241)  # Indigo
    dark = RGBColor(30, 32, 48)
    white = RGBColor(255, 255, 255)
    gray = RGBColor(160, 165, 180)

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
    _set_slide_bg(slide, dark)

    # Title text
    txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(11.333), Inches(2))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(44)
    p.font.bold = True
    p.font.color.rgb = white
    p.alignment = PP_ALIGN.CENTER

    # Subtitle
    txBox2 = slide.shapes.add_textbox(Inches(1), Inches(4.2), Inches(11.333), Inches(1))
    tf2 = txBox2.text_frame
    tf2.word_wrap = True
    p2 = tf2.paragraphs[0]
    p2.text = f"Generated on {datetime.now().strftime('%B %d, %Y')}"
    p2.font.size = Pt(18)
    p2.font.color.rgb = gray
    p2.alignment = PP_ALIGN.CENTER

    # Accent bar
    shape = slide.shapes.add_shape(
        1,  # Rectangle
        Inches(4.5), Inches(3.9), Inches(4.333), Inches(0.05)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = primary
    shape.line.fill.background()

    # Parse content into slides
    sections = _parse_sections(content)

    for section in sections:
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
        _set_slide_bg(slide, dark)

        # Accent bar at top
        bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.333), Inches(0.08))
        bar.fill.solid()
        bar.fill.fore_color.rgb = primary
        bar.line.fill.background()

        # Section heading
        heading = section.get("heading", "")
        body_lines = section.get("body", [])

        txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(11.733), Inches(1))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = heading
        p.font.size = Pt(32)
        p.font.bold = True
        p.font.color.rgb = white

        # Body content
        if body_lines:
            txBox2 = slide.shapes.add_textbox(Inches(0.8), Inches(1.8), Inches(11.733), Inches(5))
            tf2 = txBox2.text_frame
            tf2.word_wrap = True

            for i, line in enumerate(body_lines):
                if i == 0:
                    p = tf2.paragraphs[0]
                else:
                    p = tf2.add_paragraph()

                cleaned = line.strip()
                is_bullet = cleaned.startswith("- ") or cleaned.startswith("* ")
                is_numbered = bool(re.match(r"^\d+\.\s", cleaned))

                if is_bullet:
                    cleaned = cleaned[2:]
                    p.text = "  " + cleaned
                    p.level = 1
                elif is_numbered:
                    cleaned = re.sub(r"^\d+\.\s", "", cleaned)
                    p.text = cleaned
                    p.level = 1
                else:
                    p.text = cleaned

                # Remove markdown bold/italic from text
                p.text = re.sub(r"\*\*\*(.+?)\*\*\*", r"\1", p.text)
                p.text = re.sub(r"\*\*(.+?)\*\*", r"\1", p.text)
                p.text = re.sub(r"\*(.+?)\*", r"\1", p.text)

                p.font.size = Pt(18)
                p.font.color.rgb = RGBColor(220, 222, 235)
                p.space_after = Pt(8)

                # Bold parts
                if "**" in line:
                    # Re-add with formatting
                    p.clear()
                    parts = re.split(r"(\*\*.+?\*\*)", cleaned)
                    for part in parts:
                        if part.startswith("**") and part.endswith("**"):
                            run = p.add_run()
                            run.text = part[2:-2]
                            run.font.bold = True
                            run.font.size = Pt(18)
                            run.font.color.rgb = white
                        else:
                            run = p.add_run()
                            run.text = part
                            run.font.size = Pt(18)
                            run.font.color.rgb = RGBColor(220, 222, 235)

    # Thank you slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_slide_bg(slide, dark)
    txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(11.333), Inches(2))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = "Thank You"
    p.font.size = Pt(44)
    p.font.bold = True
    p.font.color.rgb = white
    p.alignment = PP_ALIGN.CENTER

    txBox2 = slide.shapes.add_textbox(Inches(1), Inches(4.5), Inches(11.333), Inches(1))
    tf2 = txBox2.text_frame
    p2 = tf2.paragraphs[0]
    p2.text = "AI Personal Assistant"
    p2.font.size = Pt(16)
    p2.font.color.rgb = gray
    p2.alignment = PP_ALIGN.CENTER

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf


def _set_slide_bg(slide, color):
    """Set slide background color."""
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _parse_sections(content: str) -> list:
    """Parse markdown content into slide sections (split by ## headings)."""
    sections = []
    current = None
    lines = content.split("\n")

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## ") or stripped.startswith("### ") or stripped.startswith("# "):
            if current:
                sections.append(current)
            heading = re.sub(r"^#{1,4}\s*", "", stripped)
            current = {"heading": heading, "body": []}
        elif current is not None:
            if stripped and not stripped.startswith("---"):
                current["body"].append(stripped)
        else:
            # Content before first heading
            if stripped and not stripped.startswith("---"):
                current = {"heading": "Overview", "body": [stripped]}

    if current:
        sections.append(current)

    # If no sections found, create one
    if not sections:
        sections = [{"heading": "Content", "body": content.split("\n")}]

    return sections
